accounts/urls.py
from django.urls import path
from .views import logout_view, login_view, register_view, UserUpdateView

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('profile/<int:pk>/', UserUpdateView.as_view(), name='profile'),
]

contacts/urls.py
from django.urls import path
from .views import FeedbackView


app_name = 'contacts'

urlpatterns = [
    path('feedback/', FeedbackView.as_view(), name='feedback'),
]

scraping_service/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from scraping.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/components/footer.html
<footer class="container-fluid">
    <p> Copyright &2024 
        <a href="https://github.com/serj2626" target="_blank" class="text-decoration-none">
            Sergey Boytsov
        </a>
    </p>
</footer>

templates/components/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5 py-2">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'home' %}"
        >Гланая</a
      >
    </li>

    {% if request.user.is_authenticated %}

    <li class="nav-item dropdown">
      <a
        class="nav-link dropdown-toggle"
        data-bs-toggle="dropdown"
        href="#"
        role="button"
        aria-expanded="false"
        >{{ request.user }}</a
      >
      <ul class="dropdown-menu">
        <li>
          <a
            class="dropdown-item"
            href="{% url 'accounts:profile' request.user.id %}"
            >Мой профиль</a
          >
        </li>
        <li>
          <a
            class="dropdown-item"
            href="{% url 'contacts:feedback' %}"
            >Форма обратной связи</a
          >
        </li>
        <li>
          <a
            class="dropdown-item"
            href="{% url 'accounts:profile' request.user.id %}"
            >Избранное</a
          >
        </li>
        <li>
          <hr class="dropdown-divider" />
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'accounts:logout' %}">Выход</a>
        </li>
      </ul>
    </li>

    {% else %}

    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:login' %}">Вход</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'accounts:register' %}">Регистрация</a>
    </li>

    {% endif %}
  </ul>
</nav>

templates/components/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show mb-4" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
</div>
{% endfor %}
{% endif %}

templates/components/vacancy_list.html
{% for vacancy in vacancys %}


<div class="card my-3">
    <div class="card-header text-center">
        {{ vacancy.title }}
    </div>
    <div class="card-title">
        <h5 class="ms-3 mt-2">{{vacancy.company }}</h5>
    </div>
    <div class="card-body">
        <h5 class="card-title my-2">
            <button type="button" class="btn btn-outline-danger disabled">{{vacancy.language.name }}</button>
        </h5>
        <p class="card-text">{{ vacancy.description | truncatechars:700 }}.</p>
        <div class="d-flex justify-content-between">
            <a target="_blank" href="{{ vacancy.url }}" class="btn btn-primary">Смотреть вакансию</a>
            <p>{{ vacancy.city.name }} | {{ vacancy.timestamp|date:"d-m-Y" }}</p>

        </div>

    </div>
</div>
{% empty %}
<div class="alert alert-warning">
    <p class="mb-0">К сожалению, вакансии отсутствуют!</p>
</div>
{% endfor %}